### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by nilsleh** [Haritha2298/INFO_VIS#1]
- [ ] COME UP With the exact visualization that we want to show in the popup window

- [x] Create Dots on map from dropdown menu

- [ ] Query points within drawn polygon

- [ ] popup window with visualization

- [ ] Create welcome page with instructions about project

- [ ] Load PanoramaPicture Dataset (geojson if possible so we can add them as markers on the map)

- [ ] Clustering datapoints on the map so it doesn't get too crowded

- [ ] figure out a way to use the issues file that cannot be used as geojson rn

- [ ] add amsterdam neighborhood polygon file as a layer

- [ ] count points by category instead of total

- [ ] for neighborhood: click on neighborhood and popup window appears

- [ ] for drawing shapes: button that triggers popup when all wanted polygons are drawn

**Comment by Haritha2298** [comment]
Added dots
